[Body]
background = "#212121"
color = "#EDEDED"
css_class = "pre"

[Comment]
color = "#666666"
font = [ "italic",]
css_class = "pre .c"

[Error]
color = "#FF0000"
font = [ "bold", "italic", "underline",]
css_class = "pre .err"

[Keyword]
color = "#F79768"
css_class = "pre .k"

[Operator]
color = "#49C7F5"
css_class = "pre .o"

["Comment.Hashbang"]
color = "#666666"
font = [ "italic",]
css_class = "pre .ch"

["Comment.Multiline"]
color = "#666666"
font = [ "italic",]
css_class = "pre .cm"

["Comment.Preproc"]
color = "#AA6666"
css_class = "pre .cp"

["Comment.PreprocFile"]
color = "#AAAA66"
font = [ "italic",]
css_class = "pre .cpf"

["Comment.Single"]
color = "#666666"
font = [ "italic",]
css_class = "pre .c1"

["Comment.Special"]
color = "#666666"
font = [ "italic",]
css_class = "pre .cs"

["Keyword.Constant"]
color = "#F5C747"
css_class = "pre .kc"

["Keyword.Declaration"]
color = "#008000"
css_class = "pre .kd"

["Keyword.Namespace"]
color = "#E061C7"
css_class = "pre .kn"

["Keyword.Pseudo"]
color = "#aa9768"
css_class = "pre .kp"

["Keyword.Reserved"]
color = "#E061C7"
css_class = "pre .kr"

["Keyword.Type"]
color = "#B00040"
css_class = "pre .kt"

["Literal.Number"]
color = "#FB9768"
css_class = "pre .m"

["Literal.Number.Bin"]
color = "#666666"
css_class = "pre .mb"

["Literal.Number.Float"]
color = "#FB9768"
css_class = "pre .mf"

["Literal.Number.Hex"]
color = "#666666"
css_class = "pre .mh"

["Literal.Number.Integer"]
color = "#FB9768"
css_class = "pre .mi"

["Literal.Number.Oct"]
color = "#666666"
css_class = "pre .mo"

["Literal.Number.Integer.Long"]
color = "#666666"
css_class = "pre .il"

["Literal.String"]
color = "#2497E3"
css_class = "pre .s"

["Literal.String.Affix"]
color = "#BA2121"
css_class = "pre .sa"

["Literal.String.Backtick"]
color = "#2497E3"
css_class = "pre .sb"

["Literal.String.Char"]
color = "#2497E3"
css_class = "pre .sc"

["Literal.String.Delimiter"]
color = "#FB9768"
css_class = "pre .dl"

["Literal.String.Doc"]
color = "#2497E3"
font = [ "italic",]
css_class = "pre .sd"

["Literal.String.Double"]
color = "#2497E3"
css_class = "pre .s2"

["Literal.String.Escape"]
color = "#F5C747"
css_class = "pre .se"

["Literal.String.Heredoc"]
color = "#2497E3"
css_class = "pre .sh"

["Literal.String.Interpol"]
color = "#FB9768"
css_class = "pre .si"

["Literal.String.Other"]
color = "#00ff00"
css_class = "pre .sx"

["Literal.String.Regex"]
color = "#2497E3"
css_class = "pre .sr"

["Literal.String.Single"]
color = "#2497E3"
css_class = "pre .s1"

["Literal.String.Symbol"]
color = "#2497E3"
css_class = "pre .ss"

["Name.Attribute"]
color = "#7D9029"
css_class = "pre .na"

["Name.Builtin"]
color = "#008800"
css_class = "pre .nb"

["Name.Class"]
color = "#E36222"
css_class = "pre .nc"

["Name.Constant"]
color = "#880000"
css_class = "pre .no"

["Name.Decorator"]
color = "#AA22FF"
css_class = "pre .nd"

["Name.Entity"]
color = "#999999"
css_class = "pre .ni"

["Name.Exception"]
color = "#D2413A"
css_class = "pre .ne"

["Name.Function"]
color = "#D65656"
css_class = "pre .nf"

["Name.Label"]
color = "#A0A000"
css_class = "pre .nl"

["Name.Namespace"]
color = "#DDDDDD"
css_class = "pre .nn"

["Name.Tag"]
color = "#008000"
css_class = "pre .nt"

["Name.Variable"]
color = "#19177C"
css_class = "pre .nv"

["Name.Builtin.Pseudo"]
color = "#F77000"
css_class = "pre .bp"

["Name.Function.Magic"]
color = "#0000FF"
css_class = "pre .fm"

["Name.Variable.Class"]
color = "#19177C"
css_class = "pre .vc"

["Name.Variable.Global"]
color = "#15B03F"
css_class = "pre .vg"

["Name.Variable.Instance"]
color = "#19177C"
css_class = "pre .vi"

["Name.Variable.Magic"]
color = "#19177C"
css_class = "pre .vm"

["Operator.Word"]
color = "#04AFBF"
css_class = "pre .ow"

["Text.Whitespace"]
color = "#BBBBBB"
css_class = "pre .w"
